export const GET_PARTNER_LIST_REQUEST = 'GET_PARTNER_LIST_REQUEST';
export const GET_PARTNER_LIST_SUCCESS = 'GET_PARTNER_LIST_SUCCESS';
export const GET_PARTNER_LIST_FAILURE = 'GET_PARTNER_LIST_FAILURE';

export function getPartnerList() {
  return {
    type: GET_PARTNER_LIST_REQUEST
  };
};